# Generated by Django 4.0.3 on 2023-02-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency1', models.FloatField()),
                ('frequency2', models.FloatField()),
                ('time1', models.FloatField()),
                ('time2', models.FloatField()),
            ],
        ),
    ]
